#!/bin/sh -Cue

# auto-parallelize redo
# note: uses jobserver from $PATH and not from repo
if which jobserver >/dev/null 2>&1; then
    jobserver started || {
        set -- "$0" "$@"
        if which jobserver-makeflags >/dev/null 2>&1; then
            set -- jobserver-makeflags "$@"
            fi
        exec jobserver init "$@"
        }
    fi

proj="$(dirname "$0")/.."
[ -d "$proj/.redo" ] || mkdir "$proj/.redo"

if [ $# != 0 ]; then
    exec redo "$@"
    fi

findr() { # find non-hidden names
    src="$1"
    shift
    find "$src" ! -name . -name '.*' -prune -o '(' "$@" ')' -print
    }

cd "$proj"
findr . -type f -name '*.link' \
| while read -r x; do
    [ -e "$x" ] || continue
    x="${x%.link}"
    case "$x" in
        ./src/*)
            printf %s\\0 "cmd/${x#./src/}"
            ;;
        *)
            printf %s\\0 "$x"
            ;;
        esac
    done \
| xargs -0 redo-ifchange
