#!/bin/sh -Cue

# auto-parallelize redo
# note: uses jobserver from $PATH and not from repo
if which jobserver >/dev/null 2>&1; then
    jobserver started || {
        set -- "$0" "$@"
        if which jobserver-makeflags >/dev/null 2>&1; then
            set -- jobserver-makeflags "$@"
            fi
        exec jobserver init "$@"
        }
    fi

proj="$(dirname "$0")/.."
[ -d "$proj/.redo" ] || mkdir "$proj/.redo"

if [ $# != 0 ]; then
    redo "$@"
else
    cd "$proj"
    for x in */*.link; do
        [ -e "$x" ] || continue
        x="${x%.link}"
        printf %s\\0 "$x"
        case "$x" in
            src/*.link)
                printf %s\\0 "cmd/${x#src/}"
                ;;
            esac
        done | xargs -0 redo-ifchange
    fi
