#!/bin/sh -ue
cd "$(dirname "$0")/.."
task/build
exec </dev/null

unset JOBSERVER
unset JOBSERVER_FDS
unset MAKEFLAGS

jobserver="$(readlink -f cmd/jobserver)"
export jobserver
_funcs="$(readlink -f test/_funcs.sh)"

run_tests() {  # [PREFIX]
    for x in *; do
        case "$x" in _*) continue ;; esac
        if [ -d "$x" ]; then
            (cd "$x" && run_tests "${1-}$x/")
            continue
            fi
        printf %s\\n "--- ${1-}$x"
        case "$x" in
            *_js.sh)
                "$jobserver" init --new \
                /bin/sh -u -e -c '. "$1"; . "$2"' test "$_funcs" "./$x"
                continue
                ;;
            *.sh)
                /bin/sh -u -e -c '. "$1"; . "$2"' test "$_funcs" "./$x"
                continue
                ;;
            esac
        if [ -x "$x" ]; then
            ./"$x"
            continue
            fi
        printf %s\\n 'unknown test type' >&2
        exit 70
        done
    }
cd test
run_tests
