#!/bin/sh -ue
#.help
# % SLOTS CMD..
MAKEFLAGS="$(printf %s "${MAKEFLAGS-}" | sed -r 's/(^| )--jobserver-(auth|fds)=[^ ]*//g') --jobserver-auth=$JOBSERVER_FDS --jobserver-fds=$JOBSERVER_FDS"
export MAKEFLAGS
count=0
release="$(dirname "$0")/release"
while [ $count -lt "$1" ]; do
    "$release"
    count=$((count + 1))
done
shift
exec "$@"
