#!/bin/sh -ue
. "$(dirname "$0")/_release"

keep_stdin=false
handle_option() {
    case "$1" in
        keep-stdin)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            keep_stdin=true
            ;;
        *) fatal 64 "unknown option $1" ;;
        esac
    }
while [ $# -gt 0 ]; do
    case "$1" in
        --) shift; break ;;
        --*=*) x="${1#--}"; handle_option "${x%%=*}" "${x#*=}"; shift ;;
        --*) handle_option "${1#--}"; shift ;;
        -?) handle_option "${1#-}"; shift ;;
        -?*)
            v="${1#??}"
            x="${1%"$v"}"
            handle_option "${x#-}" "$v"
            shift
            ;;
        *) break ;;
        esac
    done

[ $# != 0 ] || fatal 64 'missing CMD argument'
$keep_stdin || exec </dev/null
command "$@"
