#!/bin/sh -ue

fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2; exit "$rc"; }

debug=false
handle_option() {
    case "$1" in
        debug)
            [ $# = 1 ] || fatal 64 "unexpected value for option $1"
            debug=true
            ;;
        *) fatal 64 "unknown option $1" ;;
        esac
    }
while [ $# -gt 0 ]; do
    case "$1" in
        --) shift; break ;;
        --*=*) x="${1#--}"; handle_option "${x%%=*}" "${x#*=}"; shift ;;
        --*) handle_option "${1#--}"; shift ;;
        -?) handle_option "${1#-}"; shift ;;
        -?*)
            v="${1#??}"
            x="${1%"$v"}"
            handle_option "${x#-}" "$v"
            shift
            ;;
        *) break ;;
        esac
    done

[ $# = 0 ] || fatal 64 'unexpected arguments'
set -- ${MAKEFLAGS-}
found=
for x; do
    case "$x" in
        --jobserver-auth=*|--jobserver-fds=*)
            found="${x#*=}"
            ;;
        esac
    done
case "$found" in
    # this could be more explicit in that numbers are required
    ?*,?*)
        #TODO: test if these are open fds or just leftover in environ
        if $debug; then
            printf %s\\n "jobserver running; read fd: ${found%,*}, write fd: ${found#*,}"
            fi
        exit 0
        ;;
    *)
        if $debug; then
            printf %s\\n 'jobserver not running!'
            fi
        exit 1
        ;;
    esac
